php:
  build: ./docker/php
  volumes:
    - .:/var/www/symfony2biso
  links:
    - mariadb:mariadb
nginx:
  build: ./docker/nginx
  volumes_from:
    - php
  links:
    - php:php
  ports:
    - 8080:80
mariadb:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
    TERM: linux
  volumes:
    - ./docker/volumes/mariadb:/var/lib/mysql