AppBundle\Entity\Configuration:
    type: entity
    table: configuration
    indexes:
        IDX_A5E2A5D74B02ED5B:
            columns:
                - fk_market
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        keyName:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
            column: key_name
        value:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        fkMarket:
            targetEntity: Market
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_market:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
