AppBundle\Entity\Product:
    type: entity
    table: product
    indexes:
        IDX_D34A04ADDBB4BB6C:
            columns:
                - fk_seller
        IDX_D34A04AD34645A1F:
            columns:
                - fk_category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        sku:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        stock:
            type: integer
            nullable: false
            options:
                unsigned: false
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        specialPrice:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            column: special_price
        productAttributes:
            type: array
            nullable: false
            length: null
            options:
                fixed: false
            column: product_attributes
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        fkCategory:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_category:
                    referencedColumnName: id
            orphanRemoval: false
        fkSeller:
            targetEntity: Seller
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_seller:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
