AppBundle\Entity\SalesOrderItem:
    type: entity
    table: sales_order_item
    indexes:
        IDX_5DD6A86534C4B0ED:
            columns:
                - fk_order
        IDX_5DD6A86523653981:
            columns:
                - fk_product
        IDX_5DD6A865963867C1:
            columns:
                - fk_sales_order_item_status_market
        IDX_5DD6A86568E31F6:
            columns:
                - fk_sales_order_item_status_seller
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        totalAmount:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: total_amount
        marketId:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: market_id
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        additionals:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        fkProduct:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_product:
                    referencedColumnName: id
            orphanRemoval: false
        fkOrder:
            targetEntity: SalesOrder
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_order:
                    referencedColumnName: id
            orphanRemoval: false
        fkSalesOrderItemStatusSeller:
            targetEntity: SalesOrderItemStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_sales_order_item_status_seller:
                    referencedColumnName: id
            orphanRemoval: false
        fkSalesOrderItemStatusMarket:
            targetEntity: SalesOrderItemStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_sales_order_item_status_market:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
