services:
    # QUEUES
    seller_create_order:
        class: AppBundle\Application\Order\SellerCreateConsumer

    # REPOSITORIES
    order_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["AppBundle\\Infrastructure\\Order\\Order"]

    # LISTENERS
    order.queue.listener:
        class: AppBundle\Application\Order\QueueListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: seller.create.order, method: onSellerCreateOrder }

