imports:
    - { resource: services_seller.yml }
    - { resource: services_product.yml }
    - { resource: services_category.yml }
    - { resource: services_order.yml }

services:

    redis.client:
        class: Predis\Client
        arguments: ["%symfony2biso_redis_dsn%"]

    redis.log.client:
        class: Predis\Client
        arguments: ["%symfony2biso_redis_log_dsn%"]

    monolog.formatter.logstash:
        class: Monolog\Formatter\LogstashFormatter
        arguments: ["%symfony2biso_log_stash_key%"]

    monolog.handler.redis:
        class: Monolog\Handler\RedisHandler
        arguments: ["@redis.log.client", "%symfony2biso_log_redis_key%"]
        calls:
            - [setFormatter, ["@monolog.formatter.logstash"]]

    http_client:
        class: GuzzleHttp\Client

# client
    market_client:
        class: AppBundle\Infrastructure\Market\Client
        arguments: ["http_client"]


# Symfony2Biso ----------------------------------------------------------------


    app.tokens.action_listener:
        class: AppBundle\Application\Api\v1\Auth\TokenListener
        arguments: ["@market_repository", "@seller_repository"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["AppBundle\\Infrastructure\\Core\\User"]

    configuration_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["AppBundle\\Infrastructure\\Core\\Configuration"]

    market_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["AppBundle\\Infrastructure\\Core\\Market"]

