AppBundle\Infrastructure\Product\Category:
    type: entity
    table: category
    indexes:
        IDX_64C19C1DBB4BB6C:
            columns:
                - fk_seller
    uniqueConstraints:
        name_seller:
            columns:
                - name_key
                - fk_seller
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoryMarketId:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: category_seller_id
        categoryAttributes:
            type: array
            nullable: false
            length: null
            options:
                fixed: false
            column: category_attributes
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nameKey:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: name_key
    manyToOne:
        seller:
            targetEntity: AppBundle\Infrastructure\Core\Seller
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_seller:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
